### ISSUE TITLE
не работает текущая версия vkfoxx

### ISSUE THREAD

**Issue by Kyogre** [EnverOsmanov/vkfox#4]
Уже месяца два не работает текущая версия vkfoxx 5.7.13

**Comment by EnverOsmanov** [comment]
Спасибо, гляну. Скорей всего ВКонтакт отключил старую версию API.

**Comment by EnverOsmanov** [comment]
Исправлено в `5.7.14` в магазине Firefox.

**Comment by Kyogre** [comment]
подтверждаю. В 5.7.14 работа восстановлена. Благодарю!
