### ISSUE TITLE
не подтягивает авторизацию после перезапуска браузера, не загружает раздел Новости

### ISSUE THREAD

**Issue by Kyogre** [EnverOsmanov/vkfox#5]
С недавнего времени заметил две проблемы:
1. Расширение не подтягивает авторизацию после перезапуска браузера. Приходится нажимать на значок, чтобы авторизоваться.
2. В расширении не загружается список новостей (комментариев).

**Comment by EnverOsmanov** [comment]
Не смог воспроизвести.
Установил, зашёл - всё есть.
Закрыл и открыл браузер - сразу иконка стала синей.

**Comment by Kyogre** [comment]
Действительно, сейчас пункт 1 уже неактуален. Возможно, ВК починили/откатили...

Но список новостей (раздел `Мои`) всё ещё не загружается. Я правильно помню, что в этом разделе **всегда** должны загружаться последние комментарии? или всё же есть ограничение времени публикации комментариев? (например, не выводить комментарии старее полугода)

**Comment by EnverOsmanov** [comment]
На вкладке `Мои` отображааются "комментарии" и "уведомления".
Сейчас глянул документацию в ВК - период по-умолчанию - за последние 24 часа.

Параметр `start_time`:
https://dev.vk.com/method/newsfeed.getComments
https://dev.vk.com/method/notifications.get

**Comment by Kyogre** [comment]
Благодарю за объяснение. Вот как раз только что кто-то добавил комментарий на один из моих подписанных тредов, и вкладка `Мои` его успешно отобразила.
